In [1]:
cv = [1.1,2.2,1,3,4,5.4,5.5]
print(cv)

[1.1, 2.2, 1, 3, 4, 5.4, 5.5]


In [2]:
import numpy as np

In [4]:
c = np.array(cv)
print(c)

[1.1 2.2 1.  3.  4.  5.4 5.5]


In [6]:
c[2]

1.0

In [7]:
print(c*2)

[ 2.2  4.4  2.   6.   8.  10.8 11. ]


In [8]:
print(cv*2)

[1.1, 2.2, 1, 3, 4, 5.4, 5.5, 1.1, 2.2, 1, 3, 4, 5.4, 5.5]


In [9]:
print(c)

[1.1 2.2 1.  3.  4.  5.4 5.5]


In [10]:
print(cv)

[1.1, 2.2, 1, 3, 4, 5.4, 5.5]


In [11]:
type(c)

numpy.ndarray

In [12]:
type(cv)

list

In [13]:
import calendar

In [15]:
print(calendar.month(2017,11))

   November 2017
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30



In [18]:
import time
print(time.time())
print(time.sleep(5))
print(time.time())

1538061124.277872
None
1538061129.2787485


In [26]:
import sys
l=range(1000)
print(sys.getsizeof(1)*len(l))
array = np.arange(1000)
print(array.size * array.itemsize)

28000
4000


In [31]:
x= np.array([[[1,2],[2,3],[4,3]] , [[1,2],[12,1],[3,2],[1,8]]])
print(x)

[list([[1, 2], [2, 3], [4, 3]]) list([[1, 2], [12, 1], [3, 2], [1, 8]])]


In [32]:
type(x)

numpy.ndarray

In [35]:
y=np.array([[1,2,4,5],[2,3,4,3],[4,3,1,2]])
print(y)

[[1 2 4 5]
 [2 3 4 3]
 [4 3 1 2]]


In [39]:
x.shape


(2,)

In [40]:
z=np.array([[1,2],[2,3],[4,3]],dtype=complex)
z

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j],
       [4.+0.j, 3.+0.j]])

In [43]:
np.zeros((10))


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
y.min()
y.max()
y.sum()

34

In [46]:
x+y

ValueError: operands could not be broadcast together with shapes (2,) (3,4) 

# indexing and slicing


In [11]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
a[1:7]

array([2, 3, 4, 5, 6, 7])

In [16]:
a = np.array([ [1,2,3], [1,4,7], [2,5,9]])
print(a)
print(a[1,2])
print(a[1:,1])
print(a[-1])

[[1 2 3]
 [1 4 7]
 [2 5 9]]
7
[4 5]
[2 5 9]


In [17]:
for i in a:
    print(i)

[1 2 3]
[1 4 7]
[2 5 9]


In [19]:
v = np.arange(10).reshape(2,5)
print(v)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
n=np.array([[1,2],[12,21],[31,67]])
m=np.array([[4,5],[2,56],[54,32]])
print(m)
print(n)

[[ 4  5]
 [ 2 56]
 [54 32]]
[[ 1  2]
 [12 21]
 [31 67]]


In [23]:
np.vstack((m,n))


array([[ 4,  5],
       [ 2, 56],
       [54, 32],
       [ 1,  2],
       [12, 21],
       [31, 67]])

In [27]:
np.hstack((m,n))

array([[ 4,  5,  1,  2],
       [ 2, 56, 12, 21],
       [54, 32, 31, 67]])

In [32]:
k=np.arange(10).reshape(2,5)
k

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
j=k<4
j

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [34]:
k[j]

array([0, 1, 2, 3])

In [38]:
for row in k:
    for item in row:
        print(item)

0
1
2
3
4
5
6
7
8
9


check nditer for other types of iterations